packages:
  - .
extra-deps:
  - git: https://github.com/facebook/duckling.git
    commit: 59a13ff87b1aa8be6b93d387244f8636b26185c5
  - snap-core-1.0.5.1
  - snap-server-1.1.2.1
  - readable-0.3.1
  - io-streams-1.5.2.2
  - io-streams-haproxy-1.0.1.0
  - network-3.1.4.0
resolver: lts-20.26
allow-newer: true
system-ghc: true
ghc-options:
  "$everything": -fPIC
