name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run build script
        run: |
          ./build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist-and-wheels
          path: |
            target/wheels/*.tar.gz
            target/wheels/*.whl
